# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-payment # name of PVC essential for identifying the storage data
  labels:
    app: paymentdb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.

---

# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-deployment
  labels:
    app: paymentdb
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: paymentdb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: paymentdb
        tier: database
    spec:
      containers:
        - image: mysql:5.7 # image from docker-hub
          args:
            - "--ignore-db-dir=lost+found" # Workaround for https://github.com/docker-library/mysql/issues/186
          name: paymentdb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : paymentdb-secrets
                  key :  password

            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              valueFrom :
                configMapKeyRef :
                  name : paymentdb-config
                  key :  dbName


          ports:
            - containerPort: 3306
              name: paymentdb
          volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mysql-persistent-storage # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: mysql-pv-payment

---

# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
spec:
  selector:
    app: paymentdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion : v1
kind : ConfigMap
metadata:
  name : paymentdb-config
data:
  dbName: payments

---

apiVersion : v1
kind : Secret
metadata:
  name : paymentdb-secrets
data:
  username : cm9vdA==
  password : MTk4Ng==