
server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://reservation-admin:DQ53QNzEbDlKGtHb@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
      database: dev-notification
  application:
    name: notification-service

jwt:
  expiry: 300000
  secret: top-secret

account-reservation-token: 123456789