server:
  port: 8080
spring:
  kafka:
    consumer:
      bootstrap-servers:
      group-id: group_Id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers:
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  name: account-service

data:
  mongodb:
    uri: mongodb+srv://reservation-admin:DQ53QNzEbDlKGtHb@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
    database: dev-catalog

jwt:
  expiry: 300000
  secret: top-secret



