server:
  port: 8081
spring:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
  application:
    name: catalog-service

  data:
    mongodb:
      uri: mongodb+srv://reservation-admin:DQ53QNzEbDlKGtHb@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
      database: dev-catalog

kafka.bootstrap.servers: pkc-3w22w.us-central1.gcp.confluent.cloud:9092

jwt:
  expiry: 300000
  secret: top-secret


