server:
  port: 8081
spring:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVER}
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='DZVQ5N4IGPVHI2TP'   password='RL/3kOXiq8eHHWAHSz4DsueV7Y3QQ3Cev3Le8aZeBajvHQARG3OmlPy8A93HF/CF';
      security.protocol: SASL_SSL
  application:
    name: catalog-service

  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
      database: ${DB_NAME}

jwt:
  expiry: ${JWT_EXPIRY}
  secret: ${JWT_SECRET}


