apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    run: account
spec:
  selector:
    matchLabels:
      run: account
  replicas: 2
  template:
    metadata:
      labels:
        run: account
    spec:
      containers:
        - name: account
          image: amitbd1508/rental-account-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 8080
          securityContext:
            privileged: false
          env: # Setting Environment Variables
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: account-app-config
                  key: db_url

            - name: DB_PORT
              value: "3306"

            - name: SERVER_PORT
              value: "8080"

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: accountdb-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: accountdb-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: accountdb-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: account-app-secret
                  key: jwt-secret
            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: account-app-config
                  key: jwt_expire
