apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    run: reservation
spec:
  selector:
    matchLabels:
      run: reservation
  replicas: 2
  template:
    metadata:
      labels:
        run: reservation
    spec:
      containers:
        - name: reservation
          image: amitbd1508/rental-reservation-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: false
          env: # Setting Environment Variables
            - name: CATALOG_URL
              value: http://catalog-svc:80/catalogs
            - name: SERVER_PORT
              value: "8080"
