apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    run: notification
spec:
  selector:
    matchLabels:
      run: notification
  replicas: 1
  template:
    metadata:
      labels:
        run: notification
    spec:
      containers:
        - name: notification
          image: amitbd1508/rental-notification-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: false
          env: # Setting Environment Variables
            - name: SERVER_PORT
              value: "8080"

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: notification-app-config
                  key: db-name
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-server
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: password
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: username


            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-app-secret
                  key: jwt-secret
            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: notification-app-config
                  key: jwt_expire
