apiVersion: v1
kind: Secret
metadata:
  name: notification-app-secret
type: Opaque
stringData:
  username: cm9vdA==
  password: MTk4Ng==
  jwt-secret: FKckg7aj1rt9scui5ik5tr93d0FKckg7aj1rt9scui5ik5tr93d0FKckg7aj1rt9scui5ik5tr93d0
