apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
