apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    run: notification
  ports:
    - name: http
      port: 80 # Service's port
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
