server:
  port: 8080
spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb+srv://reservation-admin:DQ53QNzEbDlKGtHb@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
      database: dev-search
jwt:
  expiry: 300000
  secret: top-secret
