
server:
  port: 8080
spring:
  application:
    name: reservation-service

  data:
    mongodb:
      uri: mongodb+srv://reservation-admin:DQ53QNzEbDlKGtHb@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
      database: prod-reservation

jwt:
  expiry: 300000
  secret: top-secret

catalog.url: ${CATALOG_URL}
