apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: amitbd1508/product-service:2.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: ACCOUNT_URL
              value: http://account-svc:8080
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: product-app-config
                  key: db_url
            - name: PRODUCT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: product-app-config
                  key: product_token

            - name: DB_PORT
              value: "3306"

            - name: SERVER_PORT
              value: "8080"

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: productdb-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: product-app-secret
                  key: jwt-secret
            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: product-app-config
                  key: jwt_expire

---

apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-app-config
data:
  db_url: product-db-service
  topic-name: topic
  jwt_expire: "3600000"
  product_token: producttoken01jdskfhkd

---
apiVersion: v1
kind: Secret
metadata:
  name: product-app-secret
type: Opaque
stringData:
  username: cm9vdA==
  password: MTk4Ng==
  jwt-secret: FKckg7aj1rt9scui5ik5tr93d0FKckg7aj1rt9scui5ik5tr93d0FKckg7aj1rt9scui5ik5tr93d0

