
server:
  port: 8083
spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb+srv://reservation-admin:DQ53QNzEbDlKGtHb@cluster0.10ffeuz.mongodb.net/?retryWrites=true&w=majority
      database: dev-payment

jwt:
  expiry: 300000
  secret: top-secret


