apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: amitbd1508/vehicle-account-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Setting Environment Variables
            - name: SERVER_PORT
              value: "8080"

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: catalog-app-config
                  key: db-name
            - name: KAFKA_BOOTSTRAP_SERVER  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-server
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: catalog-app-secret
                  key: jwt-secret
            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: catalog-app-config
                  key: jwt_expire
