apiVersion: v1
kind: Service
metadata:
  name: search-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
