name: 'Build & Deploy to EKS'
on:
  push:
    branches:
      - release
env:
  EKS_REGION: ${{ secrets.EKS_REGION }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PW: ${{ secrets.DOCKER_PW }}

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      # Install Node.js dependencies
      - uses: actions/checkout@v2
      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v0
        with:
          # Replace with your Workload Identity Provider Location
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER_LOCATION}}
          # Replace with your GitHub Service Account
          service_account: ${{secrets.SERVICEACCOUNT}}
      # Login to Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      # Install Skaffold
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      # Cache skaffold image builds & config
      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      # Check AWS version and configure profile
      - name: Get auth
        uses: google-github-actions/auth@v0.4.0
        with:
          cluster_name: gke_possible-tape-183617_us-central1-a_neg-demo-cluster
          location: us-central1-a
      - name: Get pods
        run: kubectl get pods
      - name: Check gcloud version
        run: |
          gcloud --version
      - name: Get Kube context
        run: kubectl config get-contexts
      # Connect to GKS cluster
      - name: Set kubectl context to gcloud cluster
        run: kubectl config set-context gke_possible-tape-183617_us-central1-a_neg-demo-cluster
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package  -DskipTests -X
      # Build and deploy to GKE cluster
      - name: Build and then deploy to GKE cluster with Skaffold
        run: skaffold build && skaffold run
      # Verify deployment
      - name: Verify deployment
        run: kubectl get pods
